function init(self)

end

function on_message(self, message_id, message, sender)
	if message_id == hash("start_level") then
		self.level = message.level
		msg.post("/brick_generator#brick_generator", "generate_bricks", {level = self.level})
		msg.post("/chest_generator#chest_generator", "generate_chests", {level = self.level})
		msg.post("/ball_generator#ball_generator", "generate_ball") -- спавним шарик на платформе
	end
end

function on_input(self, action_id, action)

end
