go.property("speed", 10)

function init(self)
	self.ground = 5
	go.animate(go.get_id(), "position.y", go.PLAYBACK_ONCE_FORWARD, self.ground, go.EASING_OUTSINE, self.speed, 0)
end

function fixed_update(self, dt)
	--
end

function on_message(self, message_id, message, sender)
	if message_id == hash("contact_point_response") and message.group == hash("platform") then
		msg.post("/level_interface#level_interface", "loot_increase", {count = 1})
		go.delete()
	end
end
